# Generated by Django 5.1.15 on 2026-06-01 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0005_company_is_platform_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarterlyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveSmallIntegerField()),
                (
                    "target_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_targets",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quarterly_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-quarter", "user__full_name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "user", "year", "quarter"),
                        name="unique_quarterly_target_per_user_and_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quarter__gte", 1), ("quarter__lte", 4)),
                        name="quarterly_target_valid_quarter",
                    ),
                ],
            },
        ),
    ]
