# Generated by Django 5.1.15 on 2026-05-19 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


DEFAULT_COMPANY_INDUSTRIES = [
    "Construction",
    "Contracting",
    "Real Estate Development",
    "Engineering Consultancy",
    "Architecture & Interior Design",
    "Manufacturing",
    "Technology",
    "Healthcare",
]


def seed_company_industries(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    CompanyIndustry = apps.get_model("masterdata", "CompanyIndustry")

    for company in Company.objects.all():
        existing_names = set(CompanyIndustry.objects.filter(company=company).values_list("name", flat=True))
        next_position = CompanyIndustry.objects.filter(company=company).count()

        for name in DEFAULT_COMPANY_INDUSTRIES:
            if name in existing_names:
                continue
            CompanyIndustry.objects.create(company=company, name=name, position=next_position)
            next_position += 1


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_address_country_company_address_line_and_more"),
        ("masterdata", "0002_currency_name_and_seed_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_industries",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="unique_company_industry_per_company",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_company_industries, migrations.RunPython.noop),
    ]
