# Generated by Django 5.1.15 on 2026-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(default="Lead", max_length=255),
        ),
    ]
