# Generated by Django 5.1.15 on 2026-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
