# Generated by Django 5.1.15 on 2026-05-17 12:08

import django.utils.timezone
from django.db import migrations, models


def seed_roles_and_memberships(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")

    role_map = {}
    for slug, name in (
        ("platform_admin", "Platform Admin"),
        ("company_admin", "Company Admin"),
        ("user", "User"),
    ):
        role, _ = Role.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "description": f"System role: {name}.",
                "is_system": True,
            },
        )
        role_map[slug] = role

    for user in User.objects.all():
        if user.company_id:
            user.companies.add(user.company_id)
        if user.role and user.role in role_map:
            user.roles.add(role_map[user.role])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="companies.company"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.role"
            ),
        ),
        migrations.RunPython(seed_roles_and_memberships, migrations.RunPython.noop),
    ]
