# Generated by Django 5.1.15 on 2026-05-20 10:44

from django.db import migrations, models


NON_PLATFORM_PERMISSION_CODES = sorted(
    [
        "company_profile.upload_logo",
        "company_profile.update",
        "company_profile.view",
        "contacts.create",
        "contacts.delete",
        "contacts.delete_imported",
        "contacts.import_execute",
        "contacts.import_preview",
        "contacts.update",
        "contacts.view",
        "crm_companies.create",
        "crm_companies.delete",
        "crm_companies.update",
        "crm_companies.view",
        "deals.create",
        "deals.delete",
        "deals.update",
        "deals.view",
        "master_data.manage_currencies",
        "master_data.manage_industries",
        "master_data.manage_pipeline_templates",
        "master_data.restore_defaults",
        "master_data.view",
        "pipeline_statuses.manage",
        "pipelines.create",
        "pipelines.delete",
        "pipelines.update",
        "pipelines.view",
        "roles.create",
        "roles.delete",
        "roles.manage_permissions",
        "roles.update",
        "roles.view",
        "settings.access",
        "users.assign_companies",
        "users.assign_roles",
        "users.create",
        "users.delete",
        "users.update",
        "users.view",
    ]
)
ALL_PERMISSION_CODES = sorted(
    NON_PLATFORM_PERMISSION_CODES
    + [
        "companies.create",
        "companies.delete",
        "companies.update",
        "companies.view",
    ]
)


def seed_system_role_permissions(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    defaults = {
        "platform_admin": ALL_PERMISSION_CODES,
        "company_admin": NON_PLATFORM_PERMISSION_CODES,
        "user": [],
    }
    for slug, permissions in defaults.items():
        role = Role.objects.filter(slug=slug).first()
        if role:
            role.permissions = permissions
            role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_system_role_permissions, migrations.RunPython.noop),
    ]
