# Generated by Django 5.1.15 on 2026-05-20 12:05

from django.db import migrations, models


COMPANY_ADMIN_PERMISSION_CODES = sorted(
    [
        "company_profile.update",
        "company_profile.upload_logo",
        "company_profile.view",
        "contacts.create",
        "contacts.delete",
        "contacts.import_execute",
        "contacts.update",
        "contacts.view",
        "crm_companies.create",
        "crm_companies.delete",
        "crm_companies.update",
        "crm_companies.view",
        "deals.create",
        "deals.delete",
        "deals.update",
        "deals.view",
        "master_data.manage_currencies",
        "master_data.manage_industries",
        "master_data.manage_pipeline_templates",
        "master_data.restore_defaults",
        "master_data.view",
        "pipeline_statuses.manage",
        "pipelines.create",
        "pipelines.delete",
        "pipelines.update",
        "pipelines.view",
        "roles.create",
        "roles.delete",
        "roles.manage_permissions",
        "roles.update",
        "roles.view",
        "settings.access",
        "users.assign_roles",
        "users.create",
        "users.delete",
        "users.update",
        "users.view",
    ]
)


def seed_company_default_roles(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")

    for company in Company.objects.all():
        role_map = {}
        defaults = (
            ("company_admin", "Company Admin", "Default company administrator role.", COMPANY_ADMIN_PERMISSION_CODES),
            ("user", "User", "Default company user role.", []),
        )
        for slug, name, description, permissions in defaults:
            role, created = Role.objects.get_or_create(
                company=company,
                slug=slug,
                defaults={
                    "name": name,
                    "description": description,
                    "is_system": False,
                    "permissions": permissions,
                },
            )
            if created:
                role_map[slug] = role
                continue

            role.name = name
            role.description = description
            role.is_system = False
            role.permissions = permissions
            role.save(update_fields=["name", "description", "is_system", "permissions"])
            role_map[slug] = role

        company_admin_role = role_map["company_admin"]
        user_role = role_map["user"]
        for user in User.objects.filter(company=company):
            if user.role == "company_admin":
                user.roles.add(company_admin_role)
            elif user.role == "user":
                user.roles.add(user_role)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.RunPython(seed_company_default_roles, migrations.RunPython.noop),
    ]
