# Generated by Django 5.1.15 on 2026-05-20 14:10

from django.db import migrations


PIPELINE_MEMBER_PERMISSION = "pipelines.manage_members"


def grant_company_admin_pipeline_member_permission(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    for role in Role.objects.filter(slug="company_admin"):
        permissions = sorted(set((role.permissions or []) + [PIPELINE_MEMBER_PERMISSION]))
        if permissions != (role.permissions or []):
            role.permissions = permissions
            role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_role_name_alter_role_slug"),
    ]

    operations = [
        migrations.RunPython(grant_company_admin_pipeline_member_permission, migrations.RunPython.noop),
    ]
