# Generated by Django 5.1.15 on 2026-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_details_and_administration"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo_key",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
