# Generated by Django 5.1.15 on 2026-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_logo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address_country",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="company",
            name="address_line",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="address_state",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="company",
            name="employee_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
