# Generated by Django 5.1.15 on 2026-05-20 10:44

from django.db import migrations, models


def mark_platform_owner_company(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    administration_company = Company.objects.filter(name="Administration").order_by("id").first()
    if administration_company:
        administration_company.is_platform_owner = True
        administration_company.save(update_fields=["is_platform_owner"])
        return

    first_company = Company.objects.order_by("id").first()
    if first_company:
        first_company.is_platform_owner = True
        first_company.save(update_fields=["is_platform_owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_address_country_company_address_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_platform_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_platform_owner_company, migrations.RunPython.noop),
    ]
