# Generated by Django 5.1.15 on 2026-05-18 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_company_address_country_company_address_line_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=64)),
                ("phone_numbers", models.JSONField(blank=True, default=list)),
                ("address", models.TextField(blank=True)),
                ("address_country", models.CharField(blank=True, max_length=128)),
                ("address_state", models.CharField(blank=True, max_length=128)),
                ("address_line", models.TextField(blank=True)),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "tenant_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_companies",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="CRMContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=64)),
                ("status", models.CharField(default="Lead", max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "last_touch",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.crmcompany",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_crm_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_contacts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "email"],
            },
        ),
        migrations.AddConstraint(
            model_name="crmcompany",
            constraint=models.UniqueConstraint(
                fields=("tenant_company", "name"),
                name="unique_crm_company_name_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="crmcontact",
            constraint=models.UniqueConstraint(
                fields=("email", "company"), name="unique_crm_contact_email_per_company"
            ),
        ),
    ]
