# Generated by Django 5.1.15 on 2026-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_import_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmcompany",
            name="industry",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
