# Generated by Django 5.1.15 on 2026-06-01 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_crmcompany_imported_by_crmcontact_imported_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmcontactcompanylink",
            name="stage_entered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
