# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="scope_of_work",
            field=models.TextField(blank=True),
        ),
    ]
