# Generated by Django 5.1.15 on 2026-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_address_country_company_address_line_and_more"),
        ("pipelines", "0002_pipelinestatus_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pipeline",
            options={"ordering": ["kind", "name", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="pipeline",
            name="unique_pipeline_name_per_company",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="kind",
            field=models.CharField(
                choices=[("contacts", "Contacts"), ("deals", "Deals")],
                default="contacts",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                fields=("company", "kind", "name"),
                name="unique_pipeline_name_per_company_and_kind",
            ),
        ),
    ]
