# Generated by Django 5.1.15 on 2026-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0004_pipeline_created_by_pipelinemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinemember",
            name="can_manage_companies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_manage_contacts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_manage_deals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_move_contacts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_move_deals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_view_companies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_view_contacts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="can_view_deals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pipelinemember",
            name="has_full_access",
            field=models.BooleanField(default=False),
        ),
    ]
